# Generated by Django 5.0.6 on 2026-06-06 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_approval_purchaseorder_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approval",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="approval",
            name="rfq",
        ),
        migrations.RemoveField(
            model_name="approval",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="approval",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approval",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="core.vendor",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="rfq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="core.rfq",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="core.quotation",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="core.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quotation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order",
                to="core.quotation",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ISSUED", "Issued"),
                    ("ACCEPTED", "Accepted"),
                    ("DELIVERED", "Delivered"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
